### ISSUE TITLE
Problem after update 2.0.5 to 2.0.7: incompatible types: android.arch.lifecycle.LifecycleOwner cannot be converted to androidx.lifecycle.LifecycleOwner

### ISSUE THREAD

**Issue by artyom4ek** [skydoves/PowerMenu#42]
When i was updated library to 2.7.0 i have compilation error: 
`incompatible types: android.arch.lifecycle.LifecycleOwner cannot be converted to androidx.lifecycle.LifecycleOwner`

in my method:  
```
public static CustomPowerMenu getCustomDialogPowerMenu(Context context, LifecycleOwner lifecycleOwner, OnMenuItemClickListener onMenuItemClickListener, OnDismissedListener onMoreMenuDismissedListener) {R.drawable.ic_action_promotion);
        final Drawable prDrawable = ContextCompat.getDrawable(context, R.drawable.ic_action_pr);
        final String prTitle = context.getResources().getString(R.string.more_menu_item_pr);
        return new CustomPowerMenu.Builder<>(context, new IconMenuAdapter())
                .addItem(new IconPowerMenuItem(prDrawable, prTitle, false))
                .setAnimation(MenuAnimation.SHOWUP_BOTTOM_RIGHT)
                .setLifecycleOwner(lifecycleOwner) // <-compilation error
                .setShowBackground(false)
                .setOnMenuItemClickListener(onMenuItemClickListener)
                .setOnDismissListener(onMoreMenuDismissedListener)
                .build();
    }
```
My method is called from Activity:  

`PowerMenuUtils.getCustomDialogPowerMenu(this, this, onMoreMenuItemClickListener, onMoreMenuDismissedListener);`

How to check it? Or maybe roll back to 2.5.0?

**Comment by skydoves** [comment]
@artyom4ek 
Hello! I think your project is not migrated to [AndroidX](https://developer.android.com/jetpack/androidx/migrate) yet.
In that case, you should use version 2.0.5.
